export const GloLanguageEnum = {
  "aa" : { name: 'Afar', isEnuffEnabled: false },
  "ab" : { name:"Abkhazian", isEnuffEnabled: false },
  "ae" : { name: "Avestan", isEnuffEnabled: false },
  "af" : { name: "Afrikaans", isEnuffEnabled: false },
  "ak" : { name: "Akan", isEnuffEnabled: false },
  "am" : { name: "Amharic", isEnuffEnabled: false },
  "an" : { name: "Aragonese", isEnuffEnabled: false },
  "ar" : { name: "Arabic", isEnuffEnabled: false },
  "as" : { name: "Assamese", isEnuffEnabled: false },
  "av" : { name: "Avaric", isEnuffEnabled: false },
  "ay" : { name: "Aymara", isEnuffEnabled: false },
  "az" : { name: "Azerbaijani", isEnuffEnabled: false },
  "ba" : { name: "Bashkir", isEnuffEnabled: false },
  "bg" : { name: "Bulgarian", isEnuffEnabled: false },
  "bi" : { name: "Bislama", isEnuffEnabled: false },
  "bm" : { name: "Bambara", isEnuffEnabled: false },
  "bo" : { name: "Tibetan", isEnuffEnabled: false },
  "br" : { name: "Breton", isEnuffEnabled: false },
  "bs" : { name: "Bosnian", isEnuffEnabled: false },
  "ca" : { name: "Catalan", isEnuffEnabled: false },
  "ce" : { name: "Chechen", isEnuffEnabled: false },
  "ch" : { name: "Chamorro", isEnuffEnabled: false },
  "co" : { name: "Corsican", isEnuffEnabled: false },
  "cr" : { name: "Cree", isEnuffEnabled: false },
  "cs" : { name: "Czech", isEnuffEnabled: false },
  "cu" : { name: "Church Slavic", isEnuffEnabled: false },
  "cv" : { name: "Chuvash", isEnuffEnabled: false },
  "cy" : { name: "Welsh", isEnuffEnabled: false },
  "da" : { name: "Danish", isEnuffEnabled: false },
  "de" : { name: "German", isEnuffEnabled: false },
  "dv" : { name: "Divehi", isEnuffEnabled: false },
  "dz" : { name: "Dzongkha", isEnuffEnabled: false },
  "ee" : { name: "Ewe", isEnuffEnabled: false },
  "el" : { name: "Greek", isEnuffEnabled: false },
  "en" : { name: "English", isEnuffEnabled: false },
  "eo" : { name: "Esperanto", isEnuffEnabled: false },
  "es" : { name: "Spanish", isEnuffEnabled: false },
  "et" : { name: "Estonian", isEnuffEnabled: false },
  "fa" : { name: "Persian", isEnuffEnabled: false },
  "ff" : { name: "Fulah", isEnuffEnabled: false },
  "fi" : { name: "Finnish", isEnuffEnabled: false },
  "fj" : { name: "Fijian", isEnuffEnabled: false },
  "fo" : { name: "Faroese", isEnuffEnabled: false },
  "fr" : { name: "French", isEnuffEnabled: false },
  "fy" : { name: "Frisian", isEnuffEnabled: false },
  "ga" : { name: "Irish", isEnuffEnabled: false },
  "gd" : { name: "Gaelic (Scotland)", isEnuffEnabled: false },
  "gl" : { name: "Galician", isEnuffEnabled: false },
  "gn" : { name: "Guarani", isEnuffEnabled: false },
  "gu" : { name: "Gujarati", isEnuffEnabled: false },
  "gv" : { name: "Manx", isEnuffEnabled: false },
  "ha" : { name: "Hausa", isEnuffEnabled: false },
  "he" : { name: "Hebrew", isEnuffEnabled: false },
  "hi" : { name: "Hindi", isEnuffEnabled: false },
  "ho" : { name: "Hiri Motu", isEnuffEnabled: false },
  "hr" : { name: "Croatian", isEnuffEnabled: false },
  "ht" : { name: "Haitian Creole", isEnuffEnabled: true }, // 수정
  "hu" : { name: "Hungarian", isEnuffEnabled: false },
  "hy" : { name: "Armenian", isEnuffEnabled: false },
  "hz" : { name: "Herero", isEnuffEnabled: false },
  "ia" : { name: "Interlingua", isEnuffEnabled: false },
  "id" : { name: "Indonesian", isEnuffEnabled: false },
  "ie" : { name: "Interlingue", isEnuffEnabled: false },
  "ig" : { name: "Igbo", isEnuffEnabled: false },
  "ii" : { name: "Sichuan Yi", isEnuffEnabled: false },
  "ik" : { name: "Inupiaq", isEnuffEnabled: false },
  "io" : { name: "Ido", isEnuffEnabled: false },
  "is" : { name: "Icelandic", isEnuffEnabled: false },
  "it" : { name: "Italian", isEnuffEnabled: false },
  "iu" : { name: "Inuktitut", isEnuffEnabled: false },
  "ja" : { name: "Japanese", isEnuffEnabled: false },
  "jv" : { name: "Javanese", isEnuffEnabled: false },
  "ka" : { name: "Georgian", isEnuffEnabled: false },
  "kg" : { name: "Kongo", isEnuffEnabled: false },
  "ki" : { name: "Kikuyu", isEnuffEnabled: false },
  "kj" : { name: "Kuanyama", isEnuffEnabled: false },
  "kk" : { name: "Kazakh", isEnuffEnabled: false },
  "kl" : { name: "Kalaallisut", isEnuffEnabled: false },
  "km" : { name: "Central Khmer", isEnuffEnabled: false },
  "kn" : { name: "Kannada", isEnuffEnabled: false },
  "ko" : { name: "Korean", isEnuffEnabled: false },
  "kr" : { name: "Kanuri", isEnuffEnabled: false },
  "ks" : { name: "Kashmiri", isEnuffEnabled: false },
  "ku" : { name: "Kurdish", isEnuffEnabled: false },
  "kv" : { name: "Komi", isEnuffEnabled: false },
  "kw" : { name: "Cornish", isEnuffEnabled: false },
  "ky" : { name: "Kirghiz", isEnuffEnabled: false },
  "la" : { name: "Latin", isEnuffEnabled: false },
  "lb" : { name: "Luxembourgish", isEnuffEnabled: false },
  "lg" : { name: "Ganda", isEnuffEnabled: false },
  "li" : { name: "Limburgan", isEnuffEnabled: false },
  "ln" : { name: "Lingala", isEnuffEnabled: false },
  "lo" : { name: "Lao", isEnuffEnabled: false },
  "lt" : { name: "Lithuanian", isEnuffEnabled: false },
  "lu" : { name: "Luba-Katanga", isEnuffEnabled: false },
  "lv" : { name: "Latvian", isEnuffEnabled: false },
  "lzh" : { name: "Chinese (Literary)", isEnuffEnabled: false },
  "mg" : { name: "Malagasy", isEnuffEnabled: false },
  "mh" : { name: "Marshallese", isEnuffEnabled: false },
  "mi" : { name: "Maori", isEnuffEnabled: false },
  "mk" : { name: "Macedonian", isEnuffEnabled: false },
  "ml" : { name: "Malayalam", isEnuffEnabled: false },
  "mn" : { name: "Mongolian", isEnuffEnabled: false },
  "mr" : { name: "Marathi", isEnuffEnabled: false },
  "ms" : { name: "Malay", isEnuffEnabled: false },
  "mt" : { name: "Maltese", isEnuffEnabled: false },
  "my" : { name: "Burmese", isEnuffEnabled: false },
  "na" : { name: "Nauru", isEnuffEnabled: false },
  "nb" : { name: "Norwegian Bokmål", isEnuffEnabled: false },
  "nd" : { name: "North Ndebele", isEnuffEnabled: false },
  "ne" : { name: "Nepali", isEnuffEnabled: false },
  "ng" : { name: "Ndonga", isEnuffEnabled: false },
  "nl" : { name: "Dutch", isEnuffEnabled: false },
  "nn" : { name: "Norwegian Nynorsk", isEnuffEnabled: false },
  "no" : { name: "Norwegian", isEnuffEnabled: false },
  "nr" : { name: "South Ndebele", isEnuffEnabled: false },
  "nv" : { name: "Navajo", isEnuffEnabled: false },
  "ny" : { name: "Chichewa", isEnuffEnabled: false },
  "oc" : { name: "Occitan", isEnuffEnabled: false },
  "oj" : { name: "Ojibwa", isEnuffEnabled: false },
  "om" : { name: "Oromo", isEnuffEnabled: false },
  "or" : { name: "Oriya", isEnuffEnabled: false },
  "os" : { name: "Ossetic", isEnuffEnabled: false },
  "pa" : { name: "Punjabi", isEnuffEnabled: false },
  "pi" : { name: "Pali", isEnuffEnabled: false },
  "pl" : { name: "Polish", isEnuffEnabled: false },
  "ps" : { name: "Pashto", isEnuffEnabled: false },
  "pt" : { name: "Portuguese", isEnuffEnabled: false },
  "qu" : { name: "Quechua", isEnuffEnabled: false },
  "rm" : { name: "Romansh", isEnuffEnabled: false },
  "rn" : { name: "Rundi", isEnuffEnabled: false },
  "ro" : { name: "Romanian", isEnuffEnabled: false },
  "ru" : { name: "Russian", isEnuffEnabled: false },
  "rw" : { name: "Kinyarwanda", isEnuffEnabled: false },
  "sa" : { name: "Sanskrit", isEnuffEnabled: false },
  "sc" : { name: "Sardinian", isEnuffEnabled: false },
  "sd" : { name: "Sindhi", isEnuffEnabled: false },
  "se" : { name: "Northern Sami", isEnuffEnabled: false },
  "sg" : { name: "Sango", isEnuffEnabled: false },
  "si" : { name: "Sinhala", isEnuffEnabled: false },
  "sk" : { name: "Slovak", isEnuffEnabled: false },
  "sl" : { name: "Slovenian", isEnuffEnabled: false },
  "sm" : { name: "Samoan", isEnuffEnabled: false },
  "sn" : { name: "Shona", isEnuffEnabled: false },
  "so" : { name: "Somali", isEnuffEnabled: false },
  "sq" : { name: "Albanian", isEnuffEnabled: false },
  "sr" : { name: "Serbian", isEnuffEnabled: false },
  "ss" : { name: "Swati", isEnuffEnabled: false },
  "st" : { name: "Southern Sotho", isEnuffEnabled: false },
  "su" : { name: "Sundanese", isEnuffEnabled: false },
  "sv" : { name: "Swedish", isEnuffEnabled: false },
  "sw" : { name: "Swahili", isEnuffEnabled: false },
  "ta" : { name: "Tamil", isEnuffEnabled: false },
  "te" : { name: "Telugu", isEnuffEnabled: false },
  "tg" : { name: "Tajik", isEnuffEnabled: false },
  "th" : { name: "Thai", isEnuffEnabled: false },
  "ti" : { name: "Tigrinya", isEnuffEnabled: false },
  "tk" : { name: "Turkmen", isEnuffEnabled: false },
  "tl" : { name: "Tagalog", isEnuffEnabled: true },
  "tn" : { name: "Tswana", isEnuffEnabled: false },
  "to" : { name: "Tonga (Tonga Islands)", isEnuffEnabled: false },
  "tr" : { name: "Turkish", isEnuffEnabled: false },
  "ts" : { name: "Tsonga", isEnuffEnabled: false },
  "tt" : { name: "Tatar", isEnuffEnabled: false },
  "tw" : { name: "twi", isEnuffEnabled: false },
  "ty" : { name: "Tahitian", isEnuffEnabled: false },
  "ug" : { name: "Uighur", isEnuffEnabled: false },
  "uk" : { name: "Ukrainian", isEnuffEnabled: false },
  "ur" : { name: "Urdu", isEnuffEnabled: true }, // 수정
  "uz" : { name: "Uzbek", isEnuffEnabled: false },
  "ve" : { name: "Venda", isEnuffEnabled: false },
  "vi" : { name: "Vietnamese", isEnuffEnabled: false },
  "vo" : { name: "Volapük", isEnuffEnabled: false },
  "wa" : { name: "Walloon", isEnuffEnabled: false },
  "wo" : { name: "Wolof", isEnuffEnabled: false },
  "xh" : { name: "Xhosa", isEnuffEnabled: false },
  "yi" : { name: "Yiddish", isEnuffEnabled: false },
  "yo" : { name: "Yoruba", isEnuffEnabled: false },
  "yue" : { name: "Cantonese (Traditional)", isEnuffEnabled: false },
  "za" : { name: "Zhuang", isEnuffEnabled: false },
  "zu" : { name: "Zulu", isEnuffEnabled: false },
  "tlh-Latn" : { name: "Klingon", isEnuffEnabled: false },
  "tlh-Piqd" : { name: "Klingon (plqaD)", isEnuffEnabled: false },
  "kmr" : { name: "Kurdish (Northern)", isEnuffEnabled: false },
  "mn-Cyrl" : { name: "Mongolian (Cyrillic)", isEnuffEnabled: false },
  "otq" : { name: "Queretaro Otomi", isEnuffEnabled: false },
  "yua" : { name: "Yucatec Maya", isEnuffEnabled: false },
  "ceb" : { name: "Cebuano", isEnuffEnabled: false },
  "haw" : { name: "Hawaiian", isEnuffEnabled: false },
  "hmn" : { name: "Hmong", isEnuffEnabled: false },
  "ar-JO" : { name: "Arabic (Jordan)", isEnuffEnabled: false },
  "ar-LY" : { name: "Arabic (Libya)", isEnuffEnabled: false },
  "ast" : { name: "Asturian", isEnuffEnabled: false },
  "de-AT" : { name: "German (Austria)", isEnuffEnabled: false },
  "de-LI" : { name: "German (Liechtenstein)", isEnuffEnabled: false },
  "de-LU" : { name: "German (Luxembourg)", isEnuffEnabled: false },
  "de-CH" : { name: "German (Switzerland)", isEnuffEnabled: false },
  "dsb" : { name: "Lower Sorbian", isEnuffEnabled: false },
  "en-BZ" : { name: "English (Belize)", isEnuffEnabled: false },
  "en-IE" : { name: "English (Ireland)", isEnuffEnabled: false },
  "en-JM" : { name: "English (Jamaica)", isEnuffEnabled: false },
  "en-AB" : { name: "English (Scottish)", isEnuffEnabled: false },
  "en-TT" : { name: "English (Trinidad)", isEnuffEnabled: false },
  "en-WL" : { name: "English (Welsh)", isEnuffEnabled: false },
  "es-BO" : { name: "Spanish (Bolivia)", isEnuffEnabled: false },
  "es-CL" : { name: "Spanish (Chile)", isEnuffEnabled: false },
  "es-CO" : { name: "Spanish (Colombia)", isEnuffEnabled: false },
  "es-CR" : { name: "Spanish (Costa Rica)", isEnuffEnabled: false },
  "es-DO" : { name: "Spanish (Dominican Republic)", isEnuffEnabled: false },
  "es-EC" : { name: "Spanish (Ecuador)", isEnuffEnabled: false },
  "es-SV" : { name: "Spanish (El Salvador)", isEnuffEnabled: false },
  "es-GT" : { name: "Spanish (Guatemala)", isEnuffEnabled: false },
  "es-HN" : { name: "Spanish (Honduras)", isEnuffEnabled: false },
  "es-NI" : { name: "Spanish (Nicaragua)", isEnuffEnabled: false },
  "es-PA" : { name: "Spanish (Panama)", isEnuffEnabled: false },
  "es-PY" : { name: "Spanish (Paraguay)", isEnuffEnabled: false },
  "es-PE" : { name: "Spanish (Peru)", isEnuffEnabled: false },
  "es-PR" : { name: "Spanish (Puerto Rico)", isEnuffEnabled: false },
  "es-UY" : { name: "Spanish (Uruguay)", isEnuffEnabled: false },
  "es-VE" : { name: "Spanish (Venezuela)", isEnuffEnabled: false },
  "fr-LU" : { name: "French (Luxembourg)", isEnuffEnabled: false },
  "fr-CH" : { name: "French (Switzerland)", isEnuffEnabled: false },
  "en-GH" : { name: "English (Ghana)", isEnuffEnabled: false },
  "hsb" : { name: "Upper Sorbian", isEnuffEnabled: false },
  "it-CH" : { name: "Italian (Switzerland)", isEnuffEnabled: false },
  "kab" : { name: "Kabyle", isEnuffEnabled: false },
  "ro-MD" : { name: "Romanian (Republic of Moldova)", isEnuffEnabled: false },
  "ru-MD" : { name: "Russian (Republic of Moldova)", isEnuffEnabled: false },
  "sb" : { name: "Sorbian", isEnuffEnabled: false },
  "sv-FI" : { name: "Swedish (Finland)", isEnuffEnabled: false },
  "udm" : { name: "Udmurt", isEnuffEnabled: false },
  "fil" : { name: "Filipino", isEnuffEnabled: false },
  "ar-PS" : { name: "Arabic (Palestinian Authority)", isEnuffEnabled: false },
  "en-KE" : { name: "English (Kenya)", isEnuffEnabled: false },
  "en-PH" : { name: "English (Philippines)", isEnuffEnabled: false },
  "en-SG" : { name: "English (Singapore)", isEnuffEnabled: false },
  "en-TZ" : { name: "English (Tanzania)", isEnuffEnabled: false },
  "es-CU" : { name: "Spanish (Cuba)", isEnuffEnabled: false },
  "es-GQ" : { name: "Spanish (Equatorial Guinea)", isEnuffEnabled: false },
  "en-PK" : { name: "English (Pakistan)", isEnuffEnabled: false },
  "sw-KE" : { name: "Swahili (Kenya)", isEnuffEnabled: false },
  "sw-TZ" : { name: "Swahili (Tanzania)", isEnuffEnabled: false },
  "ta-MY" : { name: "Tamil (Malaysia)", isEnuffEnabled: false },
  "ta-SG" : { name: "Tamil (Singapore)", isEnuffEnabled: false },
  "ta-LK" : { name: "Tamil (Sri Lanka)", isEnuffEnabled: false },
  "af-NA": { name: "Afrikaans (Namibia)", isEnuffEnabled: true }, // start Enuff language Code
  "af-ZA": { name: "Afrikaans (South Africa)", isEnuffEnabled: true },
  "ak-GH": { name: "Akan (Ghana)", isEnuffEnabled: true },
  "sq-AL": { name: "Albanian (Albania)", isEnuffEnabled: true },
  "ar-DZ": { name: "Arabic (Algeria)", isEnuffEnabled: true },
  "ar-BH": { name: "Arabic (Bahrain)", isEnuffEnabled: true },
  "ar-EG": { name: "Arabic (Egypt)", isEnuffEnabled: true },
  "ar-IQ": { name: "Arabic (Iraq)", isEnuffEnabled: true },
  "ar-IL": { name: "Arabic (Israel)", isEnuffEnabled: true },
  "ar-KW": { name: "Arabic (Kuwait)", isEnuffEnabled: true },
  "ar-LB": { name: "Arabic (Lebanon)", isEnuffEnabled: true },
  "ar-MA": { name: "Arabic (Morocco)", isEnuffEnabled: true },
  "ar-OM": { name: "Arabic (Oman)", isEnuffEnabled: true },
  "ar-QA": { name: "Arabic (Qatar)", isEnuffEnabled: true },
  "ar-SA": { name: "Arabic (Saudi Arabia)", isEnuffEnabled: true },
  "ar-SO": { name: "Arabic (Somalia)", isEnuffEnabled: true },
  "ar-SD": { name: "Arabic (Sudan)", isEnuffEnabled: true },
  "ar-SY": { name: "Arabic (Syria)", isEnuffEnabled: true },
  "ar-TN": { name: "Arabic (Tunisia)", isEnuffEnabled: true },
  "ar-AE": { name: "Arabic (U.A.E)", isEnuffEnabled: true },
  "ar-001":{ name: "Arabic (World)", isEnuffEnabled: true },
  "ar-YE": { name: "Arabic (Yemen)", isEnuffEnabled: true },
  "hy-AM": { name: "Armenian (Armenia)", isEnuffEnabled: true },
  "as-IN": { name: "Assamese (India)", isEnuffEnabled: true },
  "az-Cyrl": { name: "Azerbaijani (Cyrillic)", isEnuffEnabled: true },
  "az-Cyrl-AZ": { name: "Azerbaijani (Cyrillic, Azerbaijan)", isEnuffEnabled: true },
  "az-Latn": { name: "Azerbaijani (Latin)", isEnuffEnabled: true },
  "az-Latn-AZ": { name: "Azerbaijani (Latin, Azerbaijan)", isEnuffEnabled: true },
  "bn" : { name: "Bengali", isEnuffEnabled: true },
  "bn-BD": { name: "Bangla (Bangladesh)", isEnuffEnabled: true },
  "bn-IN": { name: "Bangla (India)", isEnuffEnabled: true },
  "eu": { name: "Basque", isEnuffEnabled: true },
  "be": { name: "Belarusian", isEnuffEnabled: true },
  "bs-Cyrl": { name: "Bosnian (Cyrillic)", isEnuffEnabled: true },
  "bs-Latn": { name: "Bosnian (Latin)", isEnuffEnabled: true },
  "bg-BG": { name: "Bulgarian (Bulgaria)", isEnuffEnabled: true },
  "my-MM": { name: "Burmese (Myanmar)", isEnuffEnabled: true },
  "ca-ES": { name: "Catalan (Catalan)", isEnuffEnabled: true },
  "zh-Hans": { name: "Chinese (Simplified)", isEnuffEnabled: true },
  "zh-CN": { name: "Chinese (Simplified, China)", isEnuffEnabled: true },
  "zh-SG": { name: "Chinese (Simplified, Singapore)", isEnuffEnabled: true },
  "zh-Hant": { name: "Chinese (Traditional)", isEnuffEnabled: true },
  "zh-TW": { name: "Chinese (Traditional, Taiwan)", isEnuffEnabled: true },
  "hr-HR": { name: "Croatian (Croatia)", isEnuffEnabled: true },
  "cs-CZ": { name: "Czech (Czech Republic)", isEnuffEnabled: true },
  "da-DK": { name: "Danish (Denmark)", isEnuffEnabled: true },
  "nl-BE": { name: "Dutch (Belgium)", isEnuffEnabled: true },
  "nl-NL": { name: "Dutch (Netherlands)", isEnuffEnabled: true },
  "en-AU": { name: "English (Australia)", isEnuffEnabled: true },
  "en-CA": { name: "English (Canada)", isEnuffEnabled: true },
  "en-150": { name: "English (Europe)", isEnuffEnabled: true },
  "en-HK": { name: "English (Hong Kong SAR)", isEnuffEnabled: true },
  "en-IN": { name: "English (India)", isEnuffEnabled: true },
  "en-NZ": { name: "English (New Zealand)", isEnuffEnabled: true },
  "en-NG": { name: "English (Nigeria)", isEnuffEnabled: true },
  "en-ZA": { name: "English (South Africa)", isEnuffEnabled: true },
  "en-GB": { name: "English (United Kingdom)", isEnuffEnabled: true },
  "en-US": { name: "English (United States)", isEnuffEnabled: true },
  "fil-PH": { name: "Filipino (Philippines)", isEnuffEnabled: true },
  "fi-FI": { name: "Finnish (Finland)", isEnuffEnabled: true },
  "fr-BE": { name: "French (Belgium)", isEnuffEnabled: true },
  "fr-CA": { name: "French (Canada)", isEnuffEnabled: true },
  "fr-FR": { name: "French (France)", isEnuffEnabled: true },
  "gl-ES": { name: "Galician (Galician)", isEnuffEnabled: true },
  "de-DE": { name: "German (Germany)", isEnuffEnabled: true },
  "el-GR": { name: "Greek (Greece)", isEnuffEnabled: true },
  "gu-IN": { name: "Gujarati (India)", isEnuffEnabled: true },
  "ha-Latn": { name: "Hausa (Latin)", isEnuffEnabled: true },
  "he-IL": { name:"Hebrew (Israel)", isEnuffEnabled: true },
  "hi-IN": { name:"Hindi (India)", isEnuffEnabled: true },
  "hu-HU": { name:"Hungarian (Hungary)", isEnuffEnabled: true },
  "is-IS": { name:"Icelandic (Iceland)", isEnuffEnabled: true },
  "ig-NG": { name:"Igbo (Nigeria)", isEnuffEnabled: true },
  "id-ID": { name:"Indonesian (Indonesia)", isEnuffEnabled: true },
  "ga-IE": { name:"Irish (Ireland)", isEnuffEnabled: true },
  "it-IT": { name:"Italian (Italy)", isEnuffEnabled: true },
  "ja-JP": { name:"Japanese (Japan)", isEnuffEnabled: true },
  "kn-IN": { name:"Kannada (India)", isEnuffEnabled: true },
  "kk-KZ": { name:"Kazakh (Kazakhstan)", isEnuffEnabled: true },
  "km-KH": { name:"Khmer (Cambodia)", isEnuffEnabled: true },
  "ko-KR": { name:"Korean (Korea)", isEnuffEnabled: true },
  "lo-LA": { name:"Lao (Laos)", isEnuffEnabled: true },
  "lv-LV": { name:"Latvian (Latvia)", isEnuffEnabled: true },
  "lt-LT": { name:"Lithuanian (Lithuania)", isEnuffEnabled: true },
  "ms-MY": { name:"Malay (Latin, Malaysia)", isEnuffEnabled: true },
  "ml-IN": { name:"Malayalam (India)", isEnuffEnabled: true },
  "mr-IN": { name:"Marathi (India)", isEnuffEnabled: true },
  "mn-MN": { name:"Mongolian (Cyrillic, Mongolia)", isEnuffEnabled: true },
  "mn-Mong": { name: "Mongolian (Traditional Mongolian)", isEnuffEnabled: true },
  "ne-NP": { name: "Nepali (Nepal)", isEnuffEnabled: true },
  "nb-NO": { name: "Norwegian Bokmal (Norway)", isEnuffEnabled: true },
  "nn-NO": { name: "Norwegian, Nynorsk (Norway)", isEnuffEnabled: true },
  "or-IN": { name: "Odia (India)", isEnuffEnabled: true },
  "fa-IR": { name: "Persian", isEnuffEnabled: true },
  "fa-AF": { name: "Persian (Afghanistan)", isEnuffEnabled: true },
  "pl-PL": { name: "Polish (Poland)", isEnuffEnabled: true },
  "pt-BR": { name: "Portuguese (Brazil)", isEnuffEnabled: true },
  "pt-PT": { name: "Portuguese (Portugal)", isEnuffEnabled: true },
  "pa-IN": { name: "Punjabi (India)", isEnuffEnabled: true },
  "pa-Arab-PK": { name: "Punjabi (Pakistan)", isEnuffEnabled: true },
  "ro-RO": { name: "Romanian (Romania)", isEnuffEnabled: true },
  "ru-RU": { name: "Russian (Russia)", isEnuffEnabled: true },
  "sr-Cyrl": { name: "Serbian (Cyrillic)", isEnuffEnabled: true },
  "sr-Latn": { name: "Serbian (Latin)", isEnuffEnabled: true },
  "st-SA": { name: "Sesotho (South Africa)", isEnuffEnabled: true },
  "si-LK": { name: "Sinhala (Sri Lanka)", isEnuffEnabled: true },
  "sk-SK": { name: "Slovak (Slovakia)", isEnuffEnabled: true },
  "sl-SI": { name: "Slovenian (Slovenia)", isEnuffEnabled: true },
  "so-SO": { name: "Somali (Somalia)", isEnuffEnabled: true },
  "es-AR": { name: "Spanish (Argentina)", isEnuffEnabled: true },
  "es-419": { name: "Spanish (Latin America)", isEnuffEnabled: true },
  "es-MX": { name: "Spanish (Mexico)", isEnuffEnabled: true },
  "es-ES": { name: "Spanish (Spain, International Sort)", isEnuffEnabled: true },
  "es-US": { name: "Spanish (United States)", isEnuffEnabled: true },
  "sv-SE": { name: "Swedish (Sweden)", isEnuffEnabled: true },
  "syr-SY": { name: "Syriac (Syria)", isEnuffEnabled: true },
  "ta-IN": { name: "Tamil (India)", isEnuffEnabled: true },
  "te-IN": { name: "Telugu (India)", isEnuffEnabled: true },
  "th-TH": { name: "Thai (Thailand)", isEnuffEnabled: true },
  "tr-CY": { name: "Turkish (Cyprus)", isEnuffEnabled: true },
  "tr-TR": { name: "Turkish (Turkey)", isEnuffEnabled: true },
  "uk-UA": { name: "Ukrainian (Ukraine)", isEnuffEnabled: true },
  "ur-IN": { name: "Urdu (India)", isEnuffEnabled: true },
  "ur-PK": { name: "Urdu (Pakistan)", isEnuffEnabled: true },
  "uz-Cyrl-UZ": { name: "Uzbek (Cyrillic, Uzbekistan)", isEnuffEnabled: true },
  "uz-Latn-UZ": { name: "Uzbek (Latin, Uzbekistan)", isEnuffEnabled: true },
  "vi-VN": { name: "Vietnamese (Vietnam)", isEnuffEnabled: true },
  "cy-GB": { name: "Welsh (United Kingdom)", isEnuffEnabled: true },
  "xh-ZA": { name: "Xhosa (South Africa)", isEnuffEnabled: true },
  "yo-BJ": { name: "Yoruba (Benin)", isEnuffEnabled: true },
  "yo-NG": { name: "Yoruba (Nigeria)", isEnuffEnabled: true },
  "zu-ZA": { name: "Zulu (South Africa)", isEnuffEnabled: true },
  "zh-Hans-HK" : { name: "Chinese (Simplified Han, Hong Kong SAR China)", isEnuffEnabled: true },
  "zh-Hans-MO" : { name: "Chinese (Simplified Han, Macau SAR China)", isEnuffEnabled: true },
  "zh-HK" : { name: "Chinese (Traditional, Hong Kong S.A.R.)", isEnuffEnabled: true },
  "zh-MO" : { name: "Chinese (Traditional, Macao S.A.R.)", isEnuffEnabled: true },
  "yi-001" : { name: "Yiddish (World)", isEnuffEnabled: true }, // 추가
  "fr-HT" : { name: "French (Haiti)", isEnuffEnabled: true }, // 추가
  "others" : { name: "Others", isEnuffEnabled: false }
}
